test: organize
handshake-org/hnsd pull request #101
Opened 2022-10-14 17:36 UTC by pinheadmz

2022-10-22 10:53 UTC, Falci requested changes

2022-10-22 10:53 UTC, Falci commented on integration/test-util.js
> +  }
```suggestion
  async waitForSync() {
    if (!this.hnsd || !this.hnsd.killed) {
      return new Promise(resolve => setTimeout(resolve, 100))
        .then(() => this.waitForSync);
    }
  }
```

2022-10-22 10:53 UTC, Falci commented on integration/test-util.js
> +    });
```suggestion    let timer;
    this.hnsd.stdout.on('data', (data) => {
      const chunk = data.toString('ascii');

      // check for "chain (xxx)"
      const height = chunk.match(/chain \((?<height>\d+)\).*(?![\s\S]*chain)/)?.groups?.height;
      
      if (height) 
        this.hnsdHeight = parseInt(height);

      if (timer) 
        clearTimeout(timer);

      if (!this.hnsd.killed) 
        timer = setTimeout(() => {
          this.hnsd.kill();
        }, 200);
    });
```

2022-10-23 16:22 UTC, pinheadmz commented
Update: added command `make e2e` in makefile so integration tests can be launched easily from root directory

2022-10-28 06:49 UTC, rithvikvibhu approved these changes
Very cool CI with 3 platforms! Both hnsd and integration tests work great locally.
I did forget to build for regtest (like the readme mentions) and the tests just timed out with no specific errors.

Can hnsd print the network name on start? It would help identify binaries and can also make the test suite confirm that it's build with the correct network. Just an idea, not blocking this PR.

2022-10-28 06:49 UTC, rithvikvibhu commented on integration/package.json
> +  }
I know `bns` is installed because of hsd, but since the test script explicitly uses `bns`, should be be included here?

2022-10-28 13:38 UTC, pinheadmz commented
> Can hnsd print the network name on start? It would help identify binaries and can also make the test suite confirm that it's build with the correct network. Just an idea, not blocking this PR.

Yeah re-building for each network is annoying, maybe we can work that out in the future and start hnsd with a network argument. I think we need to avoid using hnsd's stdout for anything important, and using HS class won't really work either since the "API" ports will be different for each network.

I think the fastest solution to this may be a version command or something that could work like this:

```
$ hnsd --version
1.0.0 (regtest)
```

2022-10-28 14:51 UTC, pinheadmz commented
@rithvikvibhu added in 1715b09d04a2629c8c6a03cad54d48a0bbeff364


```
--> make e2e
npm --prefix ./integration/ install

up to date, audited 37 packages in 332ms

found 0 vulnerabilities
npm --prefix ./integration/ run test

> hnsd_integration_test@1.0.0 test
> bmocha --reporter spec test/*.js


  Basic sync & resolve
    1) "before all" hook

  0 passing (89ms)
  1 failing

  1) Basic sync & resolve
       "before all" hook:

      AssertionError [ERR_ASSERTION]: Network or version mismatch

      Expected values to be strictly equal:
      
      + actual - expected
      
      + '1.0.0 (main)\n'
      - '1.0.0 (regtest)\n'
                ^
      
      assert.strictEqual(
             ^

      at TestUtil.open (/Users/matthewzipkin/Desktop/work/hnsd/integration/test-util.js:36:12)
      at async Context.<anonymous> (/Users/matthewzipkin/Desktop/work/hnsd/integration/test/sync-resolve-test.js:18:5)

make: *** [e2e] Error 1
```

2022-10-28 16:49 UTC, rithvikvibhu commented
Sweet, version shows network and test fails. LGTM

2022-11-01 17:35 UTC, merged